# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Spacectl < Formula
  desc "Spacelift client and CLI"
  homepage "https://github.com/spacelift-io/spacectl"
  version "0.0.203"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/mbialon/spacectl/releases/download/v0.0.203/spacectl_0.0.203_darwin_arm64.zip"
      sha256 "f16e4265d4090fc9386c34c4a07c07111db18fa716c70880fda7ada2a9479191"

      def install
        bin.install "spacectl"
        bash_completion.install "completions/spacectl.bash" => "spacectl"
        zsh_completion.install "completions/spacectl.zsh" => "_spacectl"
        fish_completion.install "completions/spacectl.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mbialon/spacectl/releases/download/v0.0.203/spacectl_0.0.203_darwin_amd64.zip"
      sha256 "bf8746e8d8abb1138659ce85039ab8e2442006903093b626f6794ba9f9ce8afd"

      def install
        bin.install "spacectl"
        bash_completion.install "completions/spacectl.bash" => "spacectl"
        zsh_completion.install "completions/spacectl.zsh" => "_spacectl"
        fish_completion.install "completions/spacectl.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mbialon/spacectl/releases/download/v0.0.203/spacectl_0.0.203_linux_arm64.zip"
      sha256 "eb90155cf8b8a60299e5bb9863f7ce642a2f8b341c586507a82055f03c1e16fa"

      def install
        bin.install "spacectl"
        bash_completion.install "completions/spacectl.bash" => "spacectl"
        zsh_completion.install "completions/spacectl.zsh" => "_spacectl"
        fish_completion.install "completions/spacectl.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mbialon/spacectl/releases/download/v0.0.203/spacectl_0.0.203_linux_amd64.zip"
      sha256 "89458ff2b9580005b660b4cbc9306fdbbb39325eef6e6b14365a920d8d0a6246"

      def install
        bin.install "spacectl"
        bash_completion.install "completions/spacectl.bash" => "spacectl"
        zsh_completion.install "completions/spacectl.zsh" => "_spacectl"
        fish_completion.install "completions/spacectl.fish"
      end
    end
  end
end
