# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Spacectl < Formula
  desc "Spacelift client and CLI"
  homepage "https://github.com/spacelift-io/spacectl"
  version "0.0.202"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/mbialon/spacectl/releases/download/v0.0.202/spacectl_0.0.202_darwin_arm64.zip"
      sha256 "80cf4fdc1d35bb07da4c599ff97c835993a6ba50e4bcfcffb18e6430ce87730e"

      def install
        bin.install "spacectl"
        bash_completion.install "completions/spacectl.bash" => "spacectl"
        zsh_completion.install "completions/spacectl.zsh" => "_spacectl"
        fish_completion.install "completions/spacectl.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mbialon/spacectl/releases/download/v0.0.202/spacectl_0.0.202_darwin_amd64.zip"
      sha256 "a31b7bb5b7490e07b60fac61ee6e25d323243e564139cf499c7453769cea746f"

      def install
        bin.install "spacectl"
        bash_completion.install "completions/spacectl.bash" => "spacectl"
        zsh_completion.install "completions/spacectl.zsh" => "_spacectl"
        fish_completion.install "completions/spacectl.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mbialon/spacectl/releases/download/v0.0.202/spacectl_0.0.202_linux_arm64.zip"
      sha256 "3fe0a29eb5d1367f6c766e35607ffd78661f7f8200bad79a70da1df97c31b768"

      def install
        bin.install "spacectl"
        bash_completion.install "completions/spacectl.bash" => "spacectl"
        zsh_completion.install "completions/spacectl.zsh" => "_spacectl"
        fish_completion.install "completions/spacectl.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mbialon/spacectl/releases/download/v0.0.202/spacectl_0.0.202_linux_amd64.zip"
      sha256 "1803142b8c23ae746fb2e62108b0872141c3dc09da6f2ecf8166bb930c3f3338"

      def install
        bin.install "spacectl"
        bash_completion.install "completions/spacectl.bash" => "spacectl"
        zsh_completion.install "completions/spacectl.zsh" => "_spacectl"
        fish_completion.install "completions/spacectl.fish"
      end
    end
  end
end
